// slidersData.js

import { SIM_CONSTANTS } from "./simConstants.js?v=4.28";

export const slidersData = {
  display: {
    "display-type": {
      type: "radio",
      label: "Type",
      options: ["2d", "3d"],
      value: "3d", // Default to 3D
      unit: "",
    },
    "links-colors": {
      type: "radio",
      label: "Links",
      options: ["Flow", "Capacity", "Neutral", "None"],
      value: "Flow", // Default to 3D
      unit: "",
    },
    "satellite-colors": {
      type: "radio",
      label: "Satellites",
      options: ["Quad", "Zone", "Suit", "Accel", "Thrust", "Thrust%", "Thrusters", "Lasers", "Time", "Mass", "SKprop", "Totprop", "Neutral"],
      optionDescriptions: {
        Quad: "Solar-angle quadrant: which 90° sector of its orbit the satellite is in.",
        Zone: "Orbital zone: inside Earth's orbit, between Earth and Mars, outside Mars, or on the Earth/Mars planetary ring.",
        Suit: "Suitability: which planet(s) the satellite can serve — Earth, Mars, both, or neither.",
        Accel:
          "Acceleration: station-keeping acceleration a = Σ G·M/ρ² from Earth, Mars and Jupiter (the Sun is excluded — the satellite already rides the solar orbit). Log scale 1×10⁻⁷–1×10⁻³ m/s².",
        Thrust:
          "Thrust required = m·a, where m = dry mass + station-keeping propellant (post-positioning, pre-station-keeping). Log scale 0.1–1000 mN.",
        "Thrust%":
          "Thrust required as a percentage of the satellite's available thruster thrust (set near the Isp input). >100% — the satellite cannot hold station — is shown in a distinct colour.",
        Thrusters:
          "Number of thrusters the satellite carries. With 'Auto thruster count' on, planetary-ring satellites get enough thrusters to exceed their station-keeping need (log scale 1→64); everything else carries 1.",
        Lasers:
          "Number of laser terminals (optical ports) on the satellite, set per ring by 'laser ports per satellite'. Discrete colour per count.",
        Time:
          "Years the station-keeping propellant lasts at the current rate (continuously cancelling a). Greener = longer; redder = exhausted within a few years.",
        Mass:
          "Total satellite mass = dry mass (bus + laser terminals + distance-scaled solar array) + station-keeping propellant. Scale 1000–1500 kg; lighter = greener.",
        SKprop:
          "Station-keeping propellant on board (kg). Each planetary-ring sat is sized to its own a; capped by what the tank leaves after transfer + deorbit. Coloured 0 → capacity.",
        Totprop:
          "Total propellant on board (kg) = transfer + station-keeping + deorbit. Per-satellite on the Earth/Mars rings (transfer scales with each sat's SK load), per-ring elsewhere; always ≤ propellant capacity. Coloured 0 → propellant capacity.",
        Neutral: "Uniform neutral colour — no per-satellite classification.",
      },
      value: "Quad",
      unit: "",
    },
    "thrust-bodies": {
      type: "checkbox",
      label: "Iso-thrust zones (2D)",
      description:
        "Draw 20 iso-acceleration contours (log-spaced, with value labels) of the combined gravity a = Σ G·M/ρ² of the checked bodies, in the 2D view. Uncheck all to hide.",
      options: ["Sun", "Venus", "Earth", "Mars", "Jupiter"],
      optionDescriptions: {
        Sun: "Include the Sun's gravity (G·M☉/ρ²). A co-orbital relay already balances solar gravity — check this only to visualise the raw field.",
        Venus: "Include Venus's gravity.",
        Earth: "Include Earth's gravity.",
        Mars: "Include Mars's gravity.",
        Jupiter: "Include Jupiter's gravity (the dominant external perturber).",
      },
      value: "",
      unit: "",
    },
    "geostationary-orbits": {
      type: "checkbox",
      label: "Geostationary & moon orbits (2D)",
      description: "Draw, at true scale, the small orbit circle of each checked body: Earth's geostationary orbit, Mars's areostationary orbit, and the natural-moon orbits — the Moon around Earth, Phobos and Deimos around Mars. All are far smaller than the size-exaggerated planets, so zoom in to see how close they really are.",
      options: ["Earth", "Mars", "Moon", "Phobos", "Deimos"],
      value: "",
      unit: "",
    },
    "planet-orbits": {
      type: "checkbox",
      label: "Planet orbits",
      description: "Draw the true elliptical orbits of the planets (sampled from their orbital elements — eccentricity, inclination and all), in 2D and 3D.",
      options: ["Show"],
      value: "",
      unit: "",
    },
    "reference-lines": {
      type: "checkbox",
      label: "Reference lines",
      description: "Draw reference direction lines through the Sun (ending on Mars's orbit), in 2D and 3D. • Closest approach: the Earth–Mars orbits' narrowest-gap direction — the geometry-sampling 0° reference. • Mars apsides: Mars's perihelion–aphelion (major-axis) line. • Plane nodes: where Earth's and Mars's orbital planes intersect. • Earth apsides: Earth's perihelion–aphelion line.",
      options: ["Closest approach", "Mars apsides", "Plane nodes", "Earth apsides"],
      value: "",
      unit: "",
    },
    "satellite-size-factor": {
      label: "Satellite Size Factor",
      description: "Set to 0 to hide satellite meshes (links and sim still run).",
      min: 0,
      max: 64,
      value: 4,
      step: 1,
      unit: "x",
      scale: "linear",
      updateLongTermScore: false,
    },
    "planets-size-factor": {
      label: "Planets Size Factor",
      min: 0,
      max: 10,
      value: 8,
      unit: "x",
      scale: "pow2",
      steps: 11,
      updateLongTermScore: false,
    },
    "sun-size-factor": {
      label: "Sun Size Factor",
      min: 0,
      max: 10,
      value: 4,
      unit: "x",
      scale: "pow2",
      steps: 11,
      updateLongTermScore: false,
    },
    "roadster-size-factor": {
      label: "Roadster Size Factor",
      min: 0,
      max: 10,
      value: 1,
      unit: "x",
      scale: "pow2",
      steps: 11,
      updateLongTermScore: false,
    },
  },
  simulation: {
    "time-acceleration-slider": {
      label: "Time Acceleration",
      description: "0 = paused, negative = reverse. Exponential: center is 0, edges are ±2²⁴×.",
      min: -25,
      max: 25,
      value: 1,
      step: 0.1,
      unit: "x",
      scale: "signedPow2",
      updateLongTermScore: false,
    },
    // "failed-satellites-slider": {
    //   label: "Satellite failure probability",
    //   min: 0,
    //   max: 100,
    //   value: 0,
    //   step: 1,
    //   unit: "%",
    //   scale: "linear",
    //   updateLongTermScore: true,
    // },
    maxDistanceAU: {
      label: "Maximum link range AU",
      min: 0,
      max: 2,
      value: SIM_CONSTANTS.DEFAULT_MAX_DISTANCE_AU,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    maxSatCount: {
      label: "Max Satellites in Simulation",
      min: 3,
      max: 7,
      value: 5,
      step: 0.05,
      unit: "",
      scale: "pow10",
      updateLongTermScore: true,
    },
    calctimeSec: {
      label: "Allowed flow calc time",
      min: 0,
      max: 20,
      value: 5,
      step: 0.1,
      unit: " sec",
      scale: "linear",
      updateLongTermScore: true,
    },
    solarExclusionDeg: {
      label: "Solar exclusion angle",
      min: 0,
      max: 30,
      value: 5,
      step: 0.5,
      unit: "° from edge",
      scale: "linear",
      updateLongTermScore: true,
    },
    linkUpdateIntervalHours: {
      label: "Link update interval",
      description: "Sim-time between link/flow recomputations. Lower = more responsive to orbital drift, higher = less CPU. The worker prefetches the next window.",
      min: 1,
      max: 168,
      value: 24,
      step: 1,
      unit: " h",
      scale: "linear",
      updateLongTermScore: false,
    },
    "interring-matcher": {
      type: "radio",
      label: "Inter-ring matcher",
      description:
        "Algorithm pairing inner-ring sats with outer-ring sats for the concentric relay families' radial backbone. Kept selectable for comparison. linear-merge = current (forward-only merge); monotonic-wrap = forward pointer with wraparound; greedy-nearest = original shortest-distance greedy (can emit long cross-route links); greedy-merge = greedy-nearest plus an island-merge repair — an augmenting-path pass that shifts the routes between an inner-rooted partial (stalagmite) and an outer-rooted partial (stalactite) so they meet into a complete Earth→Mars route, maximising the complete-route count while preserving greedy's existing routes; periapsis-chain / periapsis-radial = seed route at the Mars-periapsis angle then a parallel neighbour sweep using every satellite — the seed hop picks the nearest sat to the previous sat (chain) or to the periapsis angle itself (radial); max-throughput = pools all rings (routes may skip rings) and greedily packs the fattest node-disjoint Earth→Mars routes first to maximise aggregate Gbps (Σ capacity of each route's longest segment); logs its realised total vs. a max-flow upper bound to the console.",
      options: ["linear-merge", "monotonic-wrap", "greedy-nearest", "greedy-merge", "periapsis-chain", "periapsis-radial", "max-throughput"],
      value: "linear-merge",
      unit: "",
      updateLongTermScore: true,
    },
    "route-continuity": {
      type: "checkbox",
      label: "Route continuity",
      description:
        "Drop radial chains that aren't a complete Earth↔Mars route. A post-pass (after planet-attach, any concentric matcher) walks each chain and removes the ones missing the required end — including their Earth/Mars planet links — since island chains carry no Earth↔Mars flow; freed terminals fall through to the lattice/spare. Check both to keep only complete routes.",
      options: ["Require inner link", "Require outer link"],
      optionDescriptions: {
        "Require inner link":
          "Require a link toward the Earth (inner) side: remove every chain that does NOT reach the Earth ring (Mars-side stubs and floating chains). Also enforced inline during greedy-nearest (a sat links outward only if it has an inward feed; innermost ring exempt).",
        "Require outer link":
          "Require a link toward the Mars (outer) side: remove every chain that does NOT reach the Mars ring (Earth-side stubs and floating chains).",
      },
      value: "",
      unit: "",
      updateLongTermScore: true,
    },
    "greedy-merge-swap-degrees": {
      label: "Island-merge swap",
      description:
        "greedy-merge matcher only: the maximum sun-angle (degrees) a fork-swap may span when joining a stalagmite to a stalactite. The repair only completes an island when it can be done by shifting a few adjacent roads within this angular window from the partial's tip; wider joins are left alone (so no long cross-links). 0 disables merging; larger merges more islands at the cost of wider lateral shifts.",
      min: 0,
      max: 30,
      value: 3,
      step: 0.5,
      unit: "°",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  launch_schedule: {
    start_year: {
      label: "Start year",
      description: "Year when launches begin (ramp from 0 starts on Jan 1 of this year).",
      min: 2025,
      max: 2040,
      value: 2028,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: false,
    },
    ramp_end_year: {
      label: "Ramp end year",
      description: "Last year of the ramp; steady-state rate is reached on Jan 1 of the following year.",
      min: 2025,
      max: 2045,
      value: 2031,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: false,
    },
    hours_between_flights: {
      label: "Hours between flights",
      description: "Steady-state launch cadence (hours between consecutive liftoffs, before scrub).",
      min: 1,
      max: 72,
      value: 8,
      step: 1,
      unit: " h",
      scale: "linear",
      updateLongTermScore: false,
    },
    scrub_factor_pct: {
      label: "Scrub factor",
      description: "Percentage of nominal launch capacity lost to scrubs.",
      min: 0,
      max: 80,
      value: 20,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: false,
    },
  },
  economics: {
    "launch-cost-slider": {
      label: "1st Starship Launch",
      description: "Cost of the first Starship/Tanker launch (before learning curve)",
      min: 1,
      max: 60,
      value: 20,
      step: 1,
      unit: "m$",
      scale: "linear",
      updateLongTermScore: false,
    },
    "satellite-cost-slider": {
      label: "1st Satellite Production",
      description: "Cost to produce the first satellite (before learning curve)",
      min: 0.1,
      max: 50,
      value: 5,
      step: 0.1,
      unit: "m$",
      scale: "linear",
      updateLongTermScore: false,
    },
    "laser-terminal-cost-slider": {
      label: "1st Laser Terminal",
      description: "Cost of the first laser terminal (before learning curve)",
      min: 0.1,
      max: 10,
      value: 0.2,
      step: 0.1,
      unit: "m$",
      scale: "linear",
      updateLongTermScore: false,
    },
    "solar-cost-per-kw": {
      label: "Solar cost",
      description: "Satellite solar-array cost per kW of power. Space-grade arrays ~$0.1–0.5M/kW.",
      min: 0,
      max: 5,
      value: 0.1,
      step: 0.05,
      unit: "m$/kW",
      scale: "linear",
      updateLongTermScore: false,
    },
    "wrights-law-factor": {
      label: "Wright's Law Factor",
      description: "Learning rate: each doubling of cumulative production reduces unit cost by this %. 100% = no learning.",
      min: 75,
      max: 100,
      value: 85,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: false,
    },
    "fuel-cost-ch4o2": {
      label: "CH4/O2 Fuel Cost",
      description: "Cost per kg of CH4/O2 propellant (launch vehicles)",
      min: 0.01,
      max: 5,
      value: 0.3,
      step: 0.01,
      unit: " $/kg",
      scale: "linear",
      updateLongTermScore: false,
    },
    "fuel-cost-argon": {
      label: "Argon Fuel Cost",
      description: "Cost per kg of Argon propellant (satellites)",
      min: 0.01,
      max: 5,
      value: 0.5,
      step: 0.01,
      unit: " $/kg",
      scale: "linear",
      updateLongTermScore: false,
    },
  },

  launch_vehicle: {
    "booster-dry-mass": { label: "Booster dry mass", description: "Super Heavy booster ~200 t empty.", min: 0, max: 1000000, value: 200000, step: 10000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "booster-propellant-capacity": { label: "Booster propellant capacity", description: "Super Heavy ~3,400 t propellant (V2 ~3,650 t).", min: 0, max: 10000000, value: 3000000, step: 100000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "booster-deorbit-propellant": { label: "Booster landing propellant", description: "Reserved for boostback + landing burns.", min: 0, max: 200000, value: 50000, step: 5000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "booster-isp": { label: "Booster engine Isp", description: "Raptor sea-level ~330 s, vacuum ~380 s.", min: 0, max: 600, value: 350, step: 5, unit: " s", scale: "linear", updateLongTermScore: true },
    "starship-dry-mass": { label: "Starship dry mass", description: "Upper stage ~100–120 t empty (V2/V3).", min: 0, max: 500000, value: 120000, step: 5000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-propellant-capacity": { label: "Starship propellant capacity", description: "V2 ~1,500 t, V3 ~2,300 t of propellant.", min: 0, max: 5000000, value: 1200000, step: 50000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-deorbit-propellant": { label: "Starship landing propellant", description: "Reserved for deorbit + landing burns.", min: 0, max: 100000, value: 20000, step: 2000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-max-payload": { label: "Starship max payload to LEO", description: "Starship V3 ~100 t, V4 ~200 t to LEO (reusable).", min: 0, max: 1000000, value: 200000, step: 10000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-isp": { label: "Starship engine Isp", description: "Raptor vacuum ~370–380 s.", min: 0, max: 600, value: 370, step: 5, unit: " s", scale: "linear", updateLongTermScore: true },
    "tanker-dry-mass": { label: "Tanker dry mass", description: "Tanker Starship variant, similar to crewed dry mass.", min: 0, max: 500000, value: 120000, step: 5000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-propellant-capacity": { label: "Tanker propellant capacity", description: "Total propellant the tanker can launch with.", min: 0, max: 5000000, value: 1200000, step: 50000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-transfer-capacity": { label: "Tanker transfer capacity", description: "Propellant delivered to the depot/ship per refuel flight (~100–150 t).", min: 0, max: 1000000, value: 200000, step: 10000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-deorbit-propellant": { label: "Tanker landing propellant", description: "Reserved for deorbit + landing burns.", min: 0, max: 100000, value: 20000, step: 2000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-isp": { label: "Tanker engine Isp", description: "Raptor vacuum ~370–380 s.", min: 0, max: 600, value: 370, step: 5, unit: " s", scale: "linear", updateLongTermScore: true },
    "launch-to-leo-dv": { label: "Launch-to-LEO Δv", description: "Surface → LEO Δv incl. losses (~9–9.5 km/s).", min: 0, max: 15, value: 9.5, step: 0.1, unit: " km/s", scale: "linear", updateLongTermScore: true },
    "escape-burn-dv": { label: "Earth-escape burn Δv", description: "LEO → Earth-SOI escape (C3=0), ~3.2 km/s.", min: 0, max: 10, value: 3.2, step: 0.1, unit: " km/s", scale: "linear", updateLongTermScore: true },
  },

  satellite: {
    "satellite-empty-mass": { label: "Satellite empty mass", description: "Dry bus mass before laser terminals, solar array, propellant and thrusters.", min: 100, max: 5000, value: 1000, step: 10, unit: " kg", scale: "linear", updateLongTermScore: true },
    "satellite-thrust": { label: "Satellite thruster thrust", description: "Max thrust per station-keeping thruster (Starlink V2 ~170 mN). Drives the 'Thrust %' colour scheme and the auto thruster count.", min: 0, max: 1000, value: 170, step: 10, unit: " mN", scale: "linear", updateLongTermScore: true },
    "thruster-system-mass": { label: "Thruster system mass", description: "Mass per thruster unit (thruster + power-processing + feed). Each thruster the satellite carries adds this much mass.", min: 0, max: 200, value: 15, step: 1, unit: " kg", scale: "linear", updateLongTermScore: true },
    "sk-years": { label: "Station-keeping years", description: "Design lifetime the station-keeping propellant is sized for (at the ring's average thrust rate). Planetary-ring sats that need more are individually sized.", min: 1, max: 15, value: 5, step: 1, unit: " yr", scale: "linear", updateLongTermScore: true },
    "max-thrusters": { label: "Max thrusters on board", description: "Cap on the number of station-keeping thrusters a satellite can carry. Sats needing more than this can't hold station (shown >100%).", min: 1, max: 128, value: 64, step: 1, unit: "", scale: "linear", updateLongTermScore: true },
    "satellite-isp": { label: "Satellite thruster Isp", description: "Electric/ion thruster ~1,500–3,000 s (Hall ~1,800 s).", min: 0, max: 5000, value: 2500, step: 50, unit: " s", scale: "linear", updateLongTermScore: true },
    "satellite-propellant-capacity": { label: "Satellite propellant capacity", description: "Onboard propellant for transfer + station-keeping + deorbit.", min: 0, max: 10000, value: 1500, step: 100, unit: " kg", scale: "linear", updateLongTermScore: true },
    "satellite-power-kw": { label: "Satellite power", description: "Total electrical power per satellite (payload + bus). Drives solar mass & cost.", min: 0, max: 50, value: 5, step: 0.5, unit: " kW", scale: "linear", updateLongTermScore: true },
    "solar-mass-per-kw": { label: "Solar specific mass", description: "Array mass per kW at Earth orbit (scaled by distance² outward). Space arrays ~5–15 kg/kW.", min: 0, max: 50, value: 10, step: 0.5, unit: " kg/kW", scale: "linear", updateLongTermScore: true },
  },

  laser_technology: {
    "current-throughput-gbps": {
      label: "Baseline throughput",
      min: 1,
      max: 999,
      value: SIM_CONSTANTS.DEFAULT_BASE_GBPS,
      step: 1,
      unit: " Gbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "current-distance-km": {
      label: "Baseline distance",
      min: 100,
      max: 10000,
      value: SIM_CONSTANTS.DEFAULT_BASE_DISTANCE_KM,
      step: 1,
      unit: " km",
      scale: "linear",
      updateLongTermScore: true,
    },
    "improvement-factor": {
      label: "Improvement factor",
      min: 0,
      max: 20,
      value: 7,
      unit: " x",
      scale: "pow2",
      steps: 21,
      updateLongTermScore: true,
    },
    "laser-terminal-mass": {
      label: "Laser Terminal Mass",
      min: 10,
      max: 500,
      value: 50,
      step: 1,
      unit: " kg",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  relay_type: {
    selected: {
      label: "Relay ring type",
      type: "radio",
      options: ["Adapted concentric", "Adapted eccentric", "Circular", "Eccentric"],
      value: "Adapted concentric",
      optionDescriptions: {
        "Adapted concentric": "Nested rings between Earth and Mars; relay traffic crosses radially ring-to-ring. The ring count sets the relay capacity.",
        "Adapted eccentric": "Ellipses tangent to both planet orbits; each ring relays Earth→Mars along its azimuthal loop. The ring count (with the in-ring rate) sets the relay capacity.",
        "Circular": "Plain concentric circular rings; relay traffic crosses radially ring-to-ring. The ring count sets the relay capacity.",
        "Eccentric": "Plain eccentric ellipses; relay traffic runs along each ring's azimuthal loop. The ring count (with the in-ring rate) sets the relay capacity.",
      },
      updateLongTermScore: true,
    },
    ringcount: {
      label: "Relay ring count",
      min: 0,
      max: 100,
      value: 26,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    planet_sizing: {
      type: "radio",
      label: "Earth/Mars auto-size",
      description:
        "How the Earth & Mars in-ring worst-case rate (their 'Throughput in ring' sliders) is set from the live relay capacity shown on the Capacity card. Each planet ring is sized to HALF the relay capacity, because a planet injects at a single gateway and its ring carries the traffic two ways. " +
        "'off': manual — set the Earth/Mars in-ring rate yourself. " +
        "'auto': keep it locked to half the live relay capacity, re-tracking whenever the relay capacity changes.",
      options: ["off", "auto"],
      value: "auto",
      unit: "",
    },
  },
  ring_earth: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 3,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "side-extension-degrees-slider": {
      label: "Side extension",
      min: 0,
      max: 180,
      value: 180,
      step: 1,
      unit: "°",
      scale: "linear",
      updateLongTermScore: true,
    },
    "match-circular-rings": {
      type: "radio",
      label: "Match Circular Rings",
      options: ["gradient", "yes", "no"],
      value: "gradient",
      unit: "",
    },

    requiredmbpsbetweensats: {
      label: "Throughput in ring (worst case)",
      description:
        "Target throughput for each in-ring laser link, sized for the worst case. Sats are evenly spaced in mean longitude, so they sit widest apart at periapsis (the planet sweeps fastest there); the sat count is chosen so even that widest periapsis link meets this throughput, guaranteeing it everywhere on the orbit.",
      min: 0,
      max: 7,
      value: 1.7,
      step: 0.005,
      unit: " Mbps",
      scale: "pow10",
      updateLongTermScore: true,
    },
  },
  ring_mars: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 3,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "side-extension-degrees-slider": {
      label: "Side extension",
      min: 0,
      max: 180,
      value: 180,
      step: 1,
      unit: "°",
      scale: "linear",
      updateLongTermScore: true,
    },
    "match-circular-rings": {
      type: "radio",
      label: "Match Circular Rings",
      options: ["gradient", "yes", "no"],
      value: "gradient",
      unit: "",
    },

    requiredmbpsbetweensats: {
      label: "Throughput in ring (worst case)",
      description:
        "Target throughput for each in-ring laser link, sized for the worst case. Sats are evenly spaced in mean longitude, so they sit widest apart at periapsis (the planet sweeps fastest there); the sat count is chosen so even that widest periapsis link meets this throughput, guaranteeing it everywhere on the orbit.",
      min: 0,
      max: 7,
      value: 1.7,
      step: 0.005,
      unit: " Mbps",
      scale: "pow10",
      updateLongTermScore: true,
    },
  },
  circular_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 4,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "flow-solver": {
      type: "radio",
      label: "Max-flow solver",
      description:
        "Algorithm that computes Earth↔Mars throughput. The 'concentric-topology-aware' fast path is specific to the Adapted-concentric family, so circular rings use a general solver.",
      options: ["push-relabel", "edmonds-karp"],
      value: "push-relabel",
      unit: "",
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 10,
      value: 0,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    requiredmbpsbetweensats: {
      label: "Throughput in ring",
      min: 1,
      max: 300,
      value: 50,
      step: 1,
      unit: " Mbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "distance-sun-slider-outer-au": {
      label: "Sun Distance Outer Ring",
      min: 0.5,
      max: 2,
      value: 1.67,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    "distance-sun-slider-inner-au": {
      label: "Sun Distance Inner Ring",
      min: 0.5,
      max: 2,
      value: 0.98,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    "inring-interring-bias-pct": {
      label: "Inring vs Inter-ring Bias",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
    "earth-mars-orbit-inclination-pct": {
      label: "Earth vs Mars inclination",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  eccentric_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 4,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "flow-solver": {
      type: "radio",
      label: "Max-flow solver",
      description:
        "Algorithm that computes Earth↔Mars throughput. 'concentric-topology-aware' only understands concentric radial chains, so eccentric rings use a general solver.",
      options: ["push-relabel", "edmonds-karp"],
      value: "push-relabel",
      unit: "",
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 16,
      value: 0,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    requiredmbpsbetweensats: {
      label: "Throughput in ring (worst case)",
      description:
        "Target throughput for each in-ring laser link, sized for the worst case. Sats are evenly spaced in mean longitude, so they sit widest apart at perihelion (the ring sweeps fastest there); the sat count is chosen so even that widest perihelion link meets this rate, guaranteeing it everywhere on the orbit.",
      min: 1,
      max: 999,
      value: 50,
      step: 1,
      unit: " Mbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "distance-sun-average-au": {
      label: "Sun Distance Average",
      min: 0.5,
      max: 2,
      value: 1.2,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    eccentricity: {
      label: "Eccentricity",
      min: 0,
      max: 1,
      value: 0.1,
      step: 0.01,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    "argument-of-perihelion": {
      label: "Argument of Perihelion",
      min: 0,
      max: 360,
      value: 336,
      step: 1,
      unit: " °",
      scale: "linear",
      updateLongTermScore: true,
    },
    "earth-mars-orbit-inclination-pct": {
      label: "Earth vs Mars inclination",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  adapted_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 5,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    lattice: {
      type: "radio",
      label: "Circular lattice",
      description:
        "How many laser terminals each satellite spends on intra-ring (azimuthal) links, on top of the radial backbone. None = all spare terminals go to spacecraft access; Half = one circular link per sat (a matching); Full = a complete azimuthal ring (two links). Lowering it frees terminals for spacecraft to attach to.",
      options: ["No circular connections", "Half lattice (1 laser terminal)", "Full lattice (2 laser terminals)"],
      value: "Full lattice (2 laser terminals)",
      unit: "",
      updateLongTermScore: true,
    },
    "flow-solver": {
      type: "radio",
      label: "Max-flow solver",
      description:
        "Algorithm that computes Earth↔Mars throughput. 'concentric-topology-aware' exploits this family's radial ring chains for speed; the general solvers work on any graph.",
      options: ["concentric-topology-aware", "push-relabel", "edmonds-karp"],
      value: "concentric-topology-aware",
      unit: "",
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 100,
      value: 26,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    "trim-rings": {
      type: "checkbox",
      label: "Trim endpoint rings",
      description: "The innermost ring (at Earth's orbit) and outermost ring (at Mars's orbit) coincide with the planet rings and are dropped by default. Uncheck to enable either endpoint ring.",
      options: ["Remove first ring", "Remove last ring"],
      value: "Remove first ring,Remove last ring",
      unit: "",
      updateLongTermScore: true,
    },
    auto_route_count: {
      type: "radio",
      label: "Auto Route Count",
      options: ["yes", "no"],
      value: "yes", // Default to yes
      unit: "",
    },
    route_count: {
      label: "Number of parallel routes",
      min: 1,
      max: 1000,
      value: 180,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
      displayCondition: { slider: "auto_route_count", value: "no" },
    },
    "satcount-density-routes": {
      label: "Sat count: density → routes",
      description:
        "How outer-ring satellite counts scale. 0% = fixed azimuthal density: satCount grows with radius (satCount ∝ a) so inter-sat spacing stays constant and outer rings carry more sats. 100% = one sat per route: every ring carries exactly the route count, giving clean 1:1 radial routes with no surplus. The innermost ring always carries the route count regardless. (Replaces the old linear satcount-increase ramp.)",
      min: 0,
      max: 100,
      value: 100,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
    "earth-mars-raan-pct": {
      label: "Earth vs Mars RAAN",
      min: 0,
      max: 100,
      value: 100,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Adapted rings' RAAN (longitude of ascending node): 0% = Earth for every satellite, 50% = interpolated by distance (Earth near Earth, Mars near Mars), 100% = Mars for every satellite.",
    },
    "earth-mars-argperi-pct": {
      label: "Earth vs Mars arg. perigee",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Adapted rings' argument of perigee: 0% = Earth for every satellite, 50% = interpolated by distance (Earth near Earth, Mars near Mars), 100% = Mars for every satellite.",
    },
    "earth-mars-eccentricity-pct": {
      label: "Earth vs Mars eccentricity",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Adapted rings' eccentricity: 0% = Earth for every satellite, 50% = interpolated by distance (Earth near Earth, Mars near Mars), 100% = Mars for every satellite.",
    },
    "earth-mars-orbit-inclination-pct": {
      label: "Earth vs Mars inclination",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
    "space-by-radius": {
      type: "radio",
      label: "Space rings by",
      description: "Which radius is distributed evenly across the range: perihelion a(1−e), semi-major axis a, or apohelion a(1+e). Each ring's a is solved to match.",
      options: ["perihelion", "a", "apohelion"],
      value: "a",
      unit: "",
    },
    "earth-endpoint-anchor": {
      type: "radio",
      label: "Earth endpoint anchor",
      description: "Which radius of Earth's orbit the inner endpoint sits at (before offset).",
      options: ["perihelion", "a", "apohelion"],
      value: "a",
      unit: "",
    },
    "mars-endpoint-anchor": {
      type: "radio",
      label: "Mars endpoint anchor",
      description: "Which radius of Mars's orbit the outer endpoint sits at (before offset).",
      options: ["perihelion", "a", "apohelion"],
      value: "a",
      unit: "",
    },
    "earth-side-offset-pct": {
      label: "Earth-side offset",
      min: -2,
      max: 2,
      value: 0.6,
      step: 0.1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Shifts the Earth-side endpoint outward (+) or inward (−) by this % of Earth's anchor radius. 0 = no offset.",
    },
    "mars-side-offset-pct": {
      label: "Mars-side offset",
      min: -2,
      max: 2,
      value: 0,
      step: 0.1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Shifts the Mars-side endpoint inward (+, into the relay area) or outward (−) by this % of Mars's anchor radius. 0 = no offset.",
    },
    "band-0-pct": {
      label: "Density · band 1 (near Earth)",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Ring-density equalizer: relative weight of the 1st of 10 bands across the Earth→Mars span (this one nearest Earth). Weights are auto-normalized and fade smoothly into neighbors; all equal = uniform spacing. Boost to pull more rings into this band.",
    },
    "band-1-pct": {
      label: "Density · band 2",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 2 of 10 across the Earth→Mars span.",
    },
    "band-2-pct": {
      label: "Density · band 3",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 3 of 10 across the Earth→Mars span.",
    },
    "band-3-pct": {
      label: "Density · band 4",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 4 of 10 across the Earth→Mars span.",
    },
    "band-4-pct": {
      label: "Density · band 5",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 5 of 10 across the Earth→Mars span.",
    },
    "band-5-pct": {
      label: "Density · band 6",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 6 of 10 across the Earth→Mars span.",
    },
    "band-6-pct": {
      label: "Density · band 7",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 7 of 10 across the Earth→Mars span.",
    },
    "band-7-pct": {
      label: "Density · band 8",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 8 of 10 across the Earth→Mars span.",
    },
    "band-8-pct": {
      label: "Density · band 9",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of band 9 of 10 across the Earth→Mars span.",
    },
    "band-9-pct": {
      label: "Density · band 10 (near Mars)",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
      description: "Relative ring-density weight of the 10th band (nearest Mars) across the Earth→Mars span.",
    },
  },
  adapted_eccentric_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 4,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "flow-solver": {
      type: "radio",
      label: "Max-flow solver",
      description:
        "Algorithm that computes Earth↔Mars throughput. 'concentric-topology-aware' only understands concentric radial chains, so adapted-eccentric rings use a general solver.",
      options: ["push-relabel", "edmonds-karp"],
      value: "push-relabel",
      unit: "",
    },
    "cross-ring-links": {
      type: "radio",
      label: "Cross-ring links",
      description:
        "Where two rings cross in the ecliptic (xy) plane, link the nearest satellite on each ring using its spare radial laser terminal (the 3rd laser, after the two in-ring neighbour links). Adds a shortcut between rings at every crossing.",
      options: ["yes", "no"],
      value: "yes",
      unit: "",
      updateLongTermScore: true,
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 100,
      value: 0,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    requiredmbpsbetweensats: {
      label: "Throughput in ring (worst case)",
      description:
        "Target throughput for each in-ring laser link, sized for the worst case (the perihelion gap, where evenly-spaced-in-mean-longitude sats sit widest apart). With the required throughput set, this is derived as throughput / (2 × ring count); set the ring count for coverage/latency and this rate carries the per-ring throughput.",
      min: 1,
      max: 999,
      value: 50,
      step: 1,
      unit: " Mbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "argument-of-perihelion": {
      label: "Argument of Perihelion (start)",
      description:
        "Ecliptic longitude of the first ring's line of apsides — the direction of its perihelion, where it touches Earth's orbit (aphelion touches Mars's orbit 180° opposite). Further rings spread evenly around 360°. Each ring's a and e are derived from Earth's and Mars's true (elliptical) distances at those apsidal longitudes, so no Sun-distance or eccentricity slider is needed.",
      min: 0,
      max: 360,
      value: 0,
      step: 1,
      unit: " °",
      scale: "linear",
      updateLongTermScore: true,
    },
    "earth-side-clearance-x": {
      label: "Earth-side clearance",
      min: 0,
      max: 0.1,
      value: 0,
      step: 0.001,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
      description:
        "Pushes each ring's perihelion this far OUTSIDE Earth's orbit, as a fixed radial gap in AU — an absolute distance, not a multiple of the varying in-ring spacing. 0 = perihelion sits exactly on Earth's orbit (touch). Raise it (e.g. 0.02 AU ≈ 3 million km) so no satellite dips inside Earth's orbit.",
    },
    "mars-side-clearance-x": {
      label: "Mars-side clearance",
      min: 0,
      max: 0.1,
      value: 0,
      step: 0.001,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
      description:
        "Pulls each ring's aphelion this far INSIDE Mars's orbit, as a fixed radial gap in AU — an absolute distance, not a multiple of the varying in-ring spacing. 0 = aphelion sits exactly on Mars's orbit (touch). Raise it (e.g. 0.02 AU ≈ 3 million km) so no satellite overshoots Mars's orbit.",
    },
    "earth-mars-orbit-inclination-pct": {
      label: "Earth vs Mars inclination",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
};
