// slidersData.js

import { SIM_CONSTANTS } from "./simConstants.js?v=4.6";

export const slidersData = {
  display: {
    "display-type": {
      type: "radio",
      label: "Type",
      options: ["2d", "3d"],
      value: "3d", // Default to 3D
      unit: "",
    },
    "links-colors": {
      type: "radio",
      label: "Links",
      options: ["Flow", "Capacity", "Grey", "None"],
      value: "Flow", // Default to 3D
      unit: "",
    },
    "satellite-colors": {
      type: "radio",
      label: "Satellites",
      options: ["Quad", "Zone", "Suit", "Grey"],
      value: "Quad",
      unit: "",
    },
    "satellite-size-factor": {
      label: "Satellite Size Factor",
      description: "Set to 0 to hide satellite meshes (links and sim still run).",
      min: 0,
      max: 64,
      value: 4,
      step: 1,
      unit: "x",
      scale: "linear",
      updateLongTermScore: false,
    },
    "planets-size-factor": {
      label: "Planets Size Factor",
      min: 0,
      max: 10,
      value: 8,
      unit: "x",
      scale: "pow2",
      steps: 11,
      updateLongTermScore: false,
    },
    "sun-size-factor": {
      label: "Sun Size Factor",
      min: 0,
      max: 10,
      value: 4,
      unit: "x",
      scale: "pow2",
      steps: 11,
      updateLongTermScore: false,
    },
    "roadster-size-factor": {
      label: "Roadster Size Factor",
      min: 0,
      max: 10,
      value: 1,
      unit: "x",
      scale: "pow2",
      steps: 11,
      updateLongTermScore: false,
    },
  },
  simulation: {
    "time-acceleration-slider": {
      label: "Time Acceleration",
      description: "0 = paused, negative = reverse. Exponential: center is 0, edges are ±2²⁴×.",
      min: -25,
      max: 25,
      value: 1,
      step: 0.1,
      unit: "x",
      scale: "signedPow2",
      updateLongTermScore: false,
    },
    // "failed-satellites-slider": {
    //   label: "Satellite failure probability",
    //   min: 0,
    //   max: 100,
    //   value: 0,
    //   step: 1,
    //   unit: "%",
    //   scale: "linear",
    //   updateLongTermScore: true,
    // },
    maxDistanceAU: {
      label: "Maximum link range AU",
      min: 0,
      max: 2,
      value: SIM_CONSTANTS.DEFAULT_MAX_DISTANCE_AU,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    maxSatCount: {
      label: "Max Satellites in Simulation",
      min: 3,
      max: 7,
      value: 5,
      step: 0.05,
      unit: "",
      scale: "pow10",
      updateLongTermScore: true,
    },
    calctimeSec: {
      label: "Allowed flow calc time",
      min: 0,
      max: 20,
      value: 5,
      step: 0.1,
      unit: " sec",
      scale: "linear",
      updateLongTermScore: true,
    },
    solarExclusionDeg: {
      label: "Solar exclusion angle",
      min: 0,
      max: 30,
      value: 5,
      step: 0.5,
      unit: "° from edge",
      scale: "linear",
      updateLongTermScore: true,
    },
    linkUpdateIntervalHours: {
      label: "Link update interval",
      description: "Sim-time between link/flow recomputations. Lower = more responsive to orbital drift, higher = less CPU. The worker prefetches the next window.",
      min: 1,
      max: 168,
      value: 24,
      step: 1,
      unit: " h",
      scale: "linear",
      updateLongTermScore: false,
    },
    flowAlgorithm: {
      type: "radio",
      label: "Max-flow algorithm",
      options: ["topology-aware", "push-relabel", "edmonds-karp"],
      value: "topology-aware",
      unit: "",
    },
  },
  launch_schedule: {
    start_year: {
      label: "Start year",
      description: "Year when launches begin (ramp from 0 starts on Jan 1 of this year).",
      min: 2025,
      max: 2040,
      value: 2028,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: false,
    },
    ramp_end_year: {
      label: "Ramp end year",
      description: "Last year of the ramp; steady-state rate is reached on Jan 1 of the following year.",
      min: 2025,
      max: 2045,
      value: 2031,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: false,
    },
    hours_between_flights: {
      label: "Hours between flights",
      description: "Steady-state launch cadence (hours between consecutive liftoffs, before scrub).",
      min: 1,
      max: 72,
      value: 8,
      step: 1,
      unit: " h",
      scale: "linear",
      updateLongTermScore: false,
    },
    scrub_factor_pct: {
      label: "Scrub factor",
      description: "Percentage of nominal launch capacity lost to scrubs.",
      min: 0,
      max: 80,
      value: 20,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: false,
    },
  },
  economics: {
    "launch-cost-slider": {
      label: "1st Starship Launch",
      description: "Cost of the first Starship/Tanker launch (before learning curve)",
      min: 1,
      max: 60,
      value: 20,
      step: 1,
      unit: "m$",
      scale: "linear",
      updateLongTermScore: false,
    },
    "satellite-cost-slider": {
      label: "1st Satellite Production",
      description: "Cost to produce the first satellite (before learning curve)",
      min: 0.1,
      max: 50,
      value: 5,
      step: 0.1,
      unit: "m$",
      scale: "linear",
      updateLongTermScore: false,
    },
    "laser-terminal-cost-slider": {
      label: "1st Laser Terminal",
      description: "Cost of the first laser terminal (before learning curve)",
      min: 0.1,
      max: 10,
      value: 0.2,
      step: 0.1,
      unit: "m$",
      scale: "linear",
      updateLongTermScore: false,
    },
    "wrights-law-factor": {
      label: "Wright's Law Factor",
      description: "Learning rate: each doubling of cumulative production reduces unit cost by this %. 100% = no learning.",
      min: 75,
      max: 100,
      value: 85,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: false,
    },
    "fuel-cost-ch4o2": {
      label: "CH4/O2 Fuel Cost",
      description: "Cost per kg of CH4/O2 propellant (launch vehicles)",
      min: 0.01,
      max: 5,
      value: 0.3,
      step: 0.01,
      unit: " $/kg",
      scale: "linear",
      updateLongTermScore: false,
    },
    "fuel-cost-argon": {
      label: "Argon Fuel Cost",
      description: "Cost per kg of Argon propellant (satellites)",
      min: 0.01,
      max: 5,
      value: 0.5,
      step: 0.01,
      unit: " $/kg",
      scale: "linear",
      updateLongTermScore: false,
    },
    "satellite-empty-mass": {
      label: "Satellite Empty Mass",
      min: 100,
      max: 5000,
      value: 1000,
      step: 10,
      unit: " kg",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  laser_technology: {
    "current-throughput-gbps": {
      label: "Baseline throughput",
      min: 1,
      max: 999,
      value: SIM_CONSTANTS.DEFAULT_BASE_GBPS,
      step: 1,
      unit: " Gbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "current-distance-km": {
      label: "Baseline distance",
      min: 100,
      max: 10000,
      value: SIM_CONSTANTS.DEFAULT_BASE_DISTANCE_KM,
      step: 1,
      unit: " km",
      scale: "linear",
      updateLongTermScore: true,
    },
    "improvement-factor": {
      label: "Improvement factor",
      min: 0,
      max: 20,
      value: 7,
      unit: " x",
      scale: "pow2",
      steps: 21,
      updateLongTermScore: true,
    },
    "laser-terminal-mass": {
      label: "Laser Terminal Mass",
      min: 10,
      max: 500,
      value: 50,
      step: 1,
      unit: " kg",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  ring_earth: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 3,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "side-extension-degrees-slider": {
      label: "Side extension",
      min: 0,
      max: 180,
      value: 180,
      step: 1,
      unit: "°",
      scale: "linear",
      updateLongTermScore: true,
    },
    "match-circular-rings": {
      type: "radio",
      label: "Match Circular Rings",
      options: ["gradient", "yes", "no"],
      value: "gradient",
      unit: "",
    },

    requiredmbpsbetweensats: {
      label: "Throughput in ring",
      min: 0,
      max: 7,
      value: 1.7,
      step: 0.05,
      unit: " Mbps",
      scale: "pow10",
      updateLongTermScore: true,
    },
  },
  ring_mars: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 3,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    "side-extension-degrees-slider": {
      label: "Side extension",
      min: 0,
      max: 180,
      value: 180,
      step: 1,
      unit: "°",
      scale: "linear",
      updateLongTermScore: true,
    },
    "match-circular-rings": {
      type: "radio",
      label: "Match Circular Rings",
      options: ["gradient", "yes", "no"],
      value: "gradient",
      unit: "",
    },

    requiredmbpsbetweensats: {
      label: "Average throughput in ring",
      min: 0,
      max: 7,
      value: 1.7,
      step: 0.05,
      unit: " Mbps",
      scale: "pow10",
      updateLongTermScore: true,
    },
  },
  circular_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 4,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 10,
      value: 0,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    requiredmbpsbetweensats: {
      label: "Throughput in ring",
      min: 1,
      max: 300,
      value: 50,
      step: 1,
      unit: " Mbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "distance-sun-slider-outer-au": {
      label: "Sun Distance Outer Ring",
      min: 0.5,
      max: 2,
      value: 1.67,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    "distance-sun-slider-inner-au": {
      label: "Sun Distance Inner Ring",
      min: 0.5,
      max: 2,
      value: 0.98,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    "inring-interring-bias-pct": {
      label: "Inring vs Inter-ring Bias",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
    "earth-mars-orbit-inclination-pct": {
      label: "Earth vs Mars inclination",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  adapted_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 2,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 100,
      value: 26,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    auto_route_count: {
      type: "radio",
      label: "Auto Route Count",
      options: ["yes", "no"],
      value: "yes", // Default to yes
      unit: "",
    },
    route_count: {
      label: "Number of parallel routes",
      min: 1,
      max: 1000,
      value: 180,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
      displayCondition: { slider: "auto_route_count", value: "no" },
    },
    linear_satcount_increase: {
      label: "Satcount increase with AU distance",
      min: 0,
      max: 2,
      value: 0.21,
      step: 0.01,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
  },
  eccentric_rings: {
    "laser-ports-per-satellite": {
      label: "Laser Terminals per Satellite",
      min: 2,
      max: 10,
      value: 4,
      step: 1,
      unit: " ports",
      scale: "linear",
      updateLongTermScore: true,
    },
    ringcount: {
      label: "Ring count",
      min: 0,
      max: 16,
      value: 0,
      step: 1,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    requiredmbpsbetweensats: {
      label: "Average throughput in ring",
      min: 1,
      max: 999,
      value: 50,
      step: 1,
      unit: " Mbps",
      scale: "linear",
      updateLongTermScore: true,
    },
    "distance-sun-average-au": {
      label: "Sun Distance Average",
      min: 0.5,
      max: 2,
      value: 1.2,
      step: 0.01,
      unit: " AU",
      scale: "linear",
      updateLongTermScore: true,
    },
    eccentricity: {
      label: "Eccentricity",
      min: 0,
      max: 1,
      value: 0.1,
      step: 0.01,
      unit: "",
      scale: "linear",
      updateLongTermScore: true,
    },
    "argument-of-perihelion": {
      label: "Argument of Perihelion",
      min: 0,
      max: 360,
      value: 336,
      step: 1,
      unit: " °",
      scale: "linear",
      updateLongTermScore: true,
    },
    "earth-mars-orbit-inclination-pct": {
      label: "Earth vs Mars inclination",
      min: 0,
      max: 100,
      value: 50,
      step: 1,
      unit: " %",
      scale: "linear",
      updateLongTermScore: true,
    },
  },

  launch_vehicle: {
    "booster-dry-mass": { label: "Booster dry mass", min: 0, max: 1000000, value: 200000, step: 10000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "booster-propellant-capacity": { label: "Booster propellant capacity", min: 0, max: 10000000, value: 3000000, step: 100000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "booster-deorbit-propellant": { label: "Booster deorbit/landing propellant", min: 0, max: 200000, value: 50000, step: 5000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "booster-isp": { label: "Booster engine Isp", min: 0, max: 600, value: 350, step: 5, unit: " s", scale: "linear", updateLongTermScore: true },
    "starship-dry-mass": { label: "Starship dry mass", min: 0, max: 500000, value: 120000, step: 5000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-propellant-capacity": { label: "Starship propellant capacity", min: 0, max: 5000000, value: 1200000, step: 50000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-deorbit-propellant": { label: "Starship deorbit/landing propellant", min: 0, max: 100000, value: 20000, step: 2000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-max-payload": { label: "Starship max payload", min: 0, max: 1000000, value: 200000, step: 10000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "starship-isp": { label: "Starship engine Isp", min: 0, max: 600, value: 370, step: 5, unit: " s", scale: "linear", updateLongTermScore: true },
    "tanker-dry-mass": { label: "Tanker dry mass", min: 0, max: 500000, value: 120000, step: 5000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-propellant-capacity": { label: "Tanker propellant capacity", min: 0, max: 5000000, value: 1200000, step: 50000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-transfer-capacity": { label: "Tanker transfer capacity (per tanker)", min: 0, max: 1000000, value: 200000, step: 10000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-deorbit-propellant": { label: "Tanker deorbit/landing propellant", min: 0, max: 100000, value: 20000, step: 2000, unit: " kg", scale: "linear", updateLongTermScore: true },
    "tanker-isp": { label: "Tanker engine Isp", min: 0, max: 600, value: 370, step: 5, unit: " s", scale: "linear", updateLongTermScore: true },
    "satellite-propellant-capacity": { label: "Satellite propellant capacity", min: 0, max: 10000, value: 1500, step: 100, unit: " kg", scale: "linear", updateLongTermScore: true },
    "satellite-isp": { label: "Satellite thruster Isp", min: 0, max: 5000, value: 2500, step: 50, unit: " s", scale: "linear", updateLongTermScore: true },
    "satellite-solar-panel-mass": { label: "Satellite solar-panel mass (Earth orbit)", min: 0, max: 500, value: 50, step: 5, unit: " kg", scale: "linear", updateLongTermScore: true },
    "launch-to-leo-dv": { label: "Launch-to-LEO Δv", min: 0, max: 15, value: 9.5, step: 0.1, unit: " km/s", scale: "linear", updateLongTermScore: true },
    "escape-burn-dv": { label: "Earth-escape burn Δv", min: 0, max: 10, value: 3.2, step: 0.1, unit: " km/s", scale: "linear", updateLongTermScore: true },
  },
};
